### ISSUE TITLE
"Integrate" the stack components

### ISSUE THREAD

**Issue by MasterOfTheBus** [MasterOfTheBus/FunStuff#5]
Do separately

push one of the work spaces in

**Comment by chubchubcharles** [comment]
I used this resource in the process:
* ["How to get started on the MEAN stack" - HackHands](https://hackhands.com/how-to-get-started-on-the-mean-stack/)

but they use Angular 1, so we might encounter incompatible information if we use Angular 2 along the way.

**The sequels in the tutorial series**:
* ["Delving into Node.js and Express web framework" - HackHands](https://hackhands.com/delving-node-js-express-web-framework/) - TODO
* ["MongoDB CRUD the MVC way with Passport Authentication" - HackHands](https://hackhands.com/mongodb-crud-mvc-way-with-passport-authentication/) - TODO


**I suggest we complete all the TODOs above and also #6 before we consider this issue closed (or if more tasks are required as they arise). Open for discussion, please comment below!**

**Comment by chubchubcharles** [comment]
**UPDATE:**
I have finished most of the **HackHands tutorial** up to the **basic login authentication**, which allows users to register, login, and logout. The rest of the tutorial talks about how to use **Basic OAuth** for **Facebook** and **Twitter API**, which is kind of irrelevant to our app at this point. So therefore, I stopped. 

I feel like I have a *wobbly grasp* of **Express.js** and **Passport.js** in the realm of cookie sessions. So I may have to read more into this later on. However, I think since the bare skeleton for a website app is in place. 

**We can start to focus on specific features and implementation of the algorithm.**

**Comment by chubchubcharles** [comment]
@MasterOfTheBus close this issue when you've finished going through the tutorial as well

**Comment by MasterOfTheBus** [comment]
I went through all three parts of the tutorial as well, but implemented using "exercises" instead of users.

**Comment by chubchubcharles** [comment]
Damn we're on a roll! 👍
